# This file should store OpenAPI v3 metadata (https://www.openapis.org/) in either JSON or YAML format.
# Ref 1: OpenAPI v3 specifications:
#        https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md
# Ref 2: SmartAPI extensions (extra fields starting with "x-")
#        https://github.com/SmartAPI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md
#        You can also refer to this list of SmartAPI extensions (excluding all OpenAPI fields):
#        https://github.com/SmartAPI/smartAPI-Specification/blob/OpenAPI.next/versions/smartapi-list.md
#
# Or the simple way to get started is to follow our examples in this repo:
#   1. This is a minimal example for MyGene.info API:
#      https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_minimum.yml
#   2. This is a full metadata example for MyGene.info API
#      https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_full.yml
